name: Pull Request Trigger

on:
  pull_request:
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Node.js script
        run: |
          npm install
          node pull-event-handler.js
          
          
          
  if-merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Run Node.js script
        run: |
          npm install
          node pull-event-handler.js
